language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm test
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: bD0tOf1zGzmejoia6kqBxusFcbT7HN9/gIzFKOECIvhTkRWGzp9NVSp3Mtmr6KleTjV5vAZ6pt3Y/LK+ORIk7g+4z4AkRnahnoWzBUTzBBNjXVc+IPU8BCAS+ef7epaHwb9eZNk2/uSheD6F7AdrrnGWDwiigYcfxP6DdP6I5CJZKzICgT8HwYkrgjSvukSkUr4Y/vWEJNP0r+XzyjhzFZTr9tsCGRbFGBIbjZ6f/urXopXdTSeIrJe7s/Bb51oB4I0cIQyz4EM12cOSa7L7ZTW24WLtBWoxMARt2VuLYcVkSJaEhQl5U2YcsmVPsr9Krys0UTHiulv6Nur3p41bfjnnasDL05jCqOcf3XyvC+u3gpcqb1x+ChjTS4sTSkYuq02I7xSTnu4iFILvs5lRRoLYFmGQB58yRiJqezO0BrtW05ZJG5o7SeVbnoCt49kOtPl4NVWX2+E0Hz0umQehTkMTVWiZsn9bWULzc5Ioi7muJBRbiI11IMwxBZVMqflA+/R+b7lKmHlW+IZqJs50Ux3z7o+yRzrErIfNxRizBAVBfKhGzX3ky7QnAQp9q3/r9ANgDRcsPeTDbIZRSAt6yWBpAVV2zXXJIhtj34t0wcPbLdbIJ80lG+Djb7oLWGhCAXrAR+Vi0zSoPn6RPexi4c49AX2t5IvaDCdM8yFmg/M=
  app: text-analyze
  on:
    branch: main
