language: node_js
node_js:
- 10.13.0
install:
- npm install
script:
- npm test
branches:
  only:
  - main
deploy:
  provider: heroku
  api_key:
    secure: FtZxQOwhe4TA9kwfSgxYqGdb51/o87SGDnJRBT5N9dMeNjkin2W09Olp66HoChS48koJS59aS9vGWvg4WW+yosiHIahJboYz3ZlsIQAz2ehH8ex2nxvuOwc+Dzu6gvu4djz9Ug3pUdtzR6X+PBkTmR65IAwEVMGUXNtLYn/saFB6TwNWW0HDEsyBA/IgjC8wCq+YJK7Mr/Joudz/jSs4hx47IhHUgsjFqJk4GZA5N6YEpmHOVh96yDzh6mFViXgIFU/wpMNgmr+C7ATnTFu52Hqn8oVt8HEDcuV/Bv49n4UdIv0ExMQh1pGFeA/ld3VSRhhhM+t1BOjQPbBBT9VI8y7joURt9NNbUZ749vQOedaZ6wB4dU0EujwbT8TJom9rGL87w+063x9fYdChz/ShC2rGO9ufpd7OtZ/HPPALWxzB+H8eMXHpbSioENiVBQvNrHpt3i1JhMnqyqkO3e/IArzsHH0vxz8s24dCSmjwHnaCHTp+n3cfgghz4GC+Qejc35Ypvg7+8eDZuhEaPz5o966eLez7LBn0R3bGvoqk1p9N0J+M4zT8ICnHzbTnvkRTGdv2ZT8Dq+OGq66CBzrdRfUDvQlxv3bQQ3WCVbaEonyg6ub9ZbNyI6mlVsgPhPB4FL03D618rttt2rBEbIYVpBCLNpyYhNAYo8FgHTKyX/E=
  app: text-analyze-app
  on:
    branch: main
